### ISSUE TITLE
Awesome and epic initiative from bilgesubilgin-signaloid

### ISSUE THREAD

**Issue by bilgesubilgin-signaloid** [bilgesubilgin-signaloid/handson-task#8]
- [ ] 🎸 A feature from bilgesubilgin-signaloid that rocks
- [ ] ⚡ Another epic feature from bilgesubilgin-signaloid
- [ ] 🔥 Hot feature from bilgesubilgin-signaloid
